#################################################### 
###########  Collider analysis pilot   #############
####################################################

# Script for putting together the batches of participants, data collected 4 July 2024 (test and main)
# Based on existing script `pilot_preprocessing` 
# (there were 5 before with differnet data structure, needing different preprocessing, they are also brought in here)
# Then saves big data df, and also that data split out into the three probability groups

library(tidyverse)
library(rjson)
rm(list=ls())


# ---------- Get main data -----------
# Setwd for main data
setwd("../Data/batch") # as in, setwd("/Users/stephaniedroop/Documents/GitHub/gw/Collider/Data/batch")

# read in csvs 
csvList <- lapply(list.files("./"), read.csv, stringsAsFactors = F) # this gives list of 10 when you're in the wd
# csvList <- lapply(list.files("./pilot_data"), read.csv, stringsAsFactors = F)
# bind them 
dataset <- do.call(rbind, csvList) # 6650 obs of 20 vars

# Remove long strings for study id etc. Go back if you need them later
dataset <- dataset %>% select(-c(2:4,6,7)) 

# Data rows were generated by different trials, but we can get everything we need in one row
# But first we need to replace spaces with NA
dataset <- dataset %>% mutate(across(c('answer'), ~na_if(.,"")))
# Then can fill upwards to get the text answer in the same place as the trial info
dataset <- dataset %>% fill(answer, .direction = 'up')

# ---------- Get jsons of static worlds info used in experiment ------
# Get the jsons
worlds <- fromJSON(file = '../../Experiment/worlds.json')
worldsdf <- as.data.frame(worlds) # 8 obs of 132 vars
conds <- fromJSON(file = '../../Experiment/conds.json')
condsdf <- as.data.frame(conds) # 2 obs of 21 vars 

# ------------ Get pilot data -------------
# Setwd 
setwd("../../pilot_data") # as in, setwd("/Users/stephaniedroop/Documents/GitHub/gw/Collider/pilot_data")

# read in csvs 
csvList <- lapply(list.files("./"), read.csv, stringsAsFactors = F) # this gives list of 10 when you're in the wd
# csvList <- lapply(list.files("./pilot_data"), read.csv, stringsAsFactors = F)
# bind them 
dataset2 <- do.call(rbind, csvList) # 250 of 20

# Get the feedback rows and comment out 
# feedback <- dataset[dataset$rowtype=='feedback',]

# Remove long strings for study id etc. Go back if you need them later
dataset2 <- dataset2 %>% select(-c(2:4,6,7)) 

# Data rows were generated by different trials, but we can get everything we need in one row
# But first we need to replace spaces with NA
dataset2 <- dataset2 %>% mutate(across(c('answer'), ~na_if(.,"")))
# Then can fill upwards to get the text answer in the same place as the trial info
dataset2 <- dataset2 %>% fill(answer, .direction = 'up')

# --------- Get the first five pilot data -------------
pilot5 <- read.csv('../processed_data/pilot1.csv') %>% select(-1)

# Put them together
dataset <- rbind(pilot5,dataset,dataset2)

# ---------- Now analysing all data together ---------
# 6950 obs of 15

# Remove empty cols and rows
dataset <- dataset %>% select(-c(13:14))
dataset <- dataset %>% filter(cb!='NA') # Obs should be 12* no. of ppts, as each did 12 trials. 3509 of 13

# Here 3329 of 13 vars, so some did not complete. Find who is complete
s12 <- dataset %>% group_by(subject_id) %>% summarise(n=n())
# Remove these ones
rem <- filter(s12,n!=12) # 15 were removed, although maybe keep the ones with 11?
data <- dataset %>% filter(!(subject_id %in% rem$subject_id)) # leaves 3456 obs, ie from 288 ppts

# REMEMBER TO TURN ROUND THE CB ONES where cb==0 probs are 1,2,3,4 but cb==1 are 3,4,1,2
# IF WE DECIDE WE NEED IT - WE MIGHT NOT ACTUALLY - DEPENDS HOW TO COMPARE AGAINST PROBS
data <- data %>% mutate(probgroup = if_else(prob0=='10%' & prob1=='50%' | prob2=='10%' & prob3=='50%', '1', 
                                          if_else(prob0=='50%' & prob1=='80%' | prob2=='50%' & prob3=='80%', '2', '3')))

# Now reattach the number of their answer, as atm it has only recorded the text on their radio button
# First here are the arrays of possible buttons from js exp.
jobanswers <- c('The candidate had skill A',
            'The candidate did not have skill A',
            'The candidate demonstrated skill A',
            'The candidate did not demonstrate skill A',
            'The candidate had skill B',
            'The candidate did not have skill B',
            'The candidate demonstrated skill B',
            'The candidate did not demonstrate skill B')

cookanswers <- c('The chef completed the main dish',
                 'The chef did not complete the main dish',
                 'The main dish impressed the panel',
                 'The main dish did not impress the panel',
                 'The chef completed the dessert',
                 'The chef did not complete the dessert',
                 'The dessert impressed the panel',
                 'The dessert did not impress the panel')

groupanswers <- c('The lecturer attended',
                  'The lecturer did not attend',
                  'The lecturer talked about the paper',
                  'The lecturer did not talk about the paper',
                  'The postdoc attended',
                  'The postdoc did not attend',
                  'The postdoc talked about the paper',
                  'The postdoc did not talk about the paper')

# Now make a new column with the position in array of their answer
data <- data %>% mutate(ans = if_else(scenario=='job', match(data$answer, jobanswers), 
                                    if_else(scenario=='cook', match(data$answer, cookanswers),
                                            match(data$answer, groupanswers))))

# -------- Permissable actual cause analysis -----------
# Checks whether ppt's answers are permissable as per Tadeg's actual causation condition
# Then analyses by participant

# Get .possAns out of json 
js <- worldsdf %>% select(ends_with("possAns"))

# Remove .possAns string from colnames, transpose so easier to search and add 1 to every cell because js indexes from 0
colnames(js) <- sub(".possAns", "", colnames(js))
js <- t(js)
js <- js+1 # now it ranges 1:8 instead of 0:7

# Empty vec to put the answers in, same order and size as
isPerm <- rep(NA, 3456)

# (Long winded index match - would be good to know a better way)
for (k in 1:nrow(data)) 
{
  row <- data[k,]
  ttype <- row$trialtype
  ans <- row$ans
  jsvec <- js[ttype,1:8]
  isposs <- ans %in% jsvec
  isPerm[k] <- isposs
}
# Add to df1 (I checked it is right)
data <- cbind(data, isPerm)

# Now group by ppt to see if they mostly pick permissable answers
tf <- data %>% group_by(subject_id, isPerm) %>% summarise(n=n())

# Map the answers they gave to the variables 
# PROBLEM - WHAT TO DO ABOUT THE CB PROBS
data <- data %>% mutate(ansVar = if_else(ans==1|ans==2, 'A', 
                                       if_else(ans==3|ans==4, 'Au',
                                               if_else(ans==5|ans==6, 'B', 'Bu'))))

data <- data %>% mutate(ansVar2 = if_else(ans==1|ans==2, 'A', 
                                       if_else(ans==3, 'Au=1',
                                               if_else(ans==4, 'Au=0',
                                                       if_else(ans==5|ans==6, 'B', 
                                                               if_else(ans==7, 'Bu=1', 'Bu=0'))))))

data <- data %>% mutate(ansVar3 = if_else(ans==1, 'A=1',
                                        if_else(ans==2, 'A=0',
                                                if_else(ans==3, 'Au=1',
                                                if_else(ans==4, 'Au=0',
                                                        if_else(ans==5, 'B=1', 
                                                                if_else(ans==6, 'B=0',
                                                                if_else(ans==7, 'Bu=1', 'Bu=0'))))))))


# Split them by probgroup here, so they can go against the relevant model pred group for comparison
pg1 <- data %>% filter(probgroup==1) # 1121 obs of 19
pg2 <- data %>% filter(probgroup==2) # 1104 obs of 19
pg3 <- data %>% filter(probgroup==3) # 1051 obs of 19

# Now summarise. For first round of plots , do ansVar=8 to see everything, so ansVar3
# If want A=a, or just 'A', take ansVar2 later
pg1prop <- pg1 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))
pg2prop <- pg2 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))
pg3prop <- pg3 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))

# Now save
save(data, pg1, pg2, pg3, pg1prop, pg2prop, pg3prop, file="../Data/Data.Rdata")

