#################################################### 
###########  Collider analysis pilot   #############
####################################################

# Script for the second 10 ppts (there were 5 before with differnet data structure, needing different preprocessing)
# NO LONGER NEEDED AT END AUG 2024 - ALL CODE BROUGHT INTO `MAINBATCH_PREPROCESSING.R`


library(tidyverse)
library(rjson)
rm(list=ls())

# Setwd 
setwd("../../pilot_data") # as in, setwd("/Users/stephaniedroop/Documents/GitHub/gw/Collider/pilot_data")

# read in csvs 
csvList <- lapply(list.files("./"), read.csv, stringsAsFactors = F) # this gives list of 10 when you're in the wd
# csvList <- lapply(list.files("./pilot_data"), read.csv, stringsAsFactors = F)
# bind them 
dataset <- do.call(rbind, csvList) 

# Get the jsons
worlds <- fromJSON(file = '../Experiment/worlds.json')
worldsdf <- as.data.frame(worlds) # 8 obs of 132 vars
conds <- fromJSON(file = '../EXperiment/conds.json')
condsdf <- as.data.frame(conds) # 2 obs of 21 vars 

# Get the feedback rows and comment out 
# feedback <- dataset[dataset$rowtype=='feedback',]

# Remove long strings for study id etc. Go back if you need them later
dataset <- dataset %>% select(-c(2:4,6,7)) 

# Data rows were generated by different trials, but we can get everything we need in one row
# But first we need to replace spaces with NA
dataset <- dataset %>% mutate(across(c('answer'), ~na_if(.,"")))
# Then can fill upwards to get the text answer in the same place as the trial info
dataset <- dataset %>% fill(answer, .direction = 'up')

# Get the pilot data
pilot5 <- read.csv('../processed_data/pilot1.csv') %>% select(-1)
# Put them together
df1 <- rbind(pilot5,dataset)

# Remove empty cols and rows
df1 <- df1 %>% select(-c(13:14))
df1 <- df1 %>% filter(cb!='NA') # Obs should be 12* no. of ppts, as each did 12 trials

# REMEMBER TO TURN ROUND THE CB ONES where cb==0 probs are 1,2,3,4 but cb==1 are 3,4,1,2
# IF WE DECIDE WE NEED IT - WE MIGHT NOT ACTUALLY - DEPENDS HOW TO COMPARE AGAINST PROBS
df1 <- df1 %>% mutate(probgroup = if_else(prob0=='10%' & prob1=='50%' | prob2=='10%' & prob3=='50%', '1', 
                                          if_else(prob0=='50%' & prob1=='80%' | prob2=='50%' & prob3=='80%', '2', '3')))

# Now reattach the number of their answer, as atm it has only recorded the text on their radio button
# First here are the arrays of possible buttons from js exp.
jobanswers <- c('The candidate had skill A',
            'The candidate did not have skill A',
            'The candidate demonstrated skill A',
            'The candidate did not demonstrate skill A',
            'The candidate had skill B',
            'The candidate did not have skill B',
            'The candidate demonstrated skill B',
            'The candidate did not demonstrate skill B')

cookanswers <- c('The chef completed the main dish',
                 'The chef did not complete the main dish',
                 'The main dish impressed the panel',
                 'The main dish did not impress the panel',
                 'The chef completed the dessert',
                 'The chef did not complete the dessert',
                 'The dessert impressed the panel',
                 'The dessert did not impress the panel')

groupanswers <- c('The lecturer attended',
                  'The lecturer did not attend',
                  'The lecturer talked about the paper',
                  'The lecturer did not talk about the paper',
                  'The postdoc attended',
                  'The postdoc did not attend',
                  'The postdoc talked about the paper',
                  'The postdoc did not talk about the paper')

# Now make a new column with the position in array of their answer
df1 <- df1 %>% mutate(ans = if_else(scenario=='job', match(df1$answer, jobanswers), 
                                    if_else(scenario=='cook', match(df1$answer, cookanswers),
                                            match(df1$answer, groupanswers))))

# -------- Permissable actual cause analysis -----------
# Checks whether ppt's answers are permissable as per Tadeg's actual causation condition
# Then analyses by participant

# Get .possAns out of json 
js <- worldsdf %>% select(ends_with("possAns"))

# Remove .possAns string from colnames, transpose so easier to search and add 1 to every cell because js indexes from 0
colnames(js) <- sub(".possAns", "", colnames(js))
js <- t(js)
js <- js+1 # now it ranges 1:8 instead of 0:7

# Empty vec to put the answers in, same order as df1
isPerm <- rep(NA, 120)

# (Long winded index match - would be good to know a better way)
for (k in 1:nrow(df1)) 
{
  row <- df1[k,]
  ttype <- row$trialtype
  ans <- row$ans
  jsvec <- js[ttype,1:8]
  isposs <- ans %in% jsvec
  isPerm[k] <- isposs
}
# Add to df1 (I checked it is right)
df1 <- cbind(df1, isPerm)

# Now group by ppt to see if they mostly pick permissable answers
tf <- df1 %>% group_by(subject_id, isPerm) %>% summarise(n=n())

# Map the answers they gave to the variables 
# PROBLEM - WHAT TO DO ABOUT THE CB PROBS
df1 <- df1 %>% mutate(ansVar = if_else(ans==1|ans==2, 'A', 
                                       if_else(ans==3|ans==4, 'Au',
                                               if_else(ans==5|ans==6, 'B', 'Bu'))))

df1 <- df1 %>% mutate(ansVar2 = if_else(ans==1|ans==2, 'A', 
                                       if_else(ans==3, 'Au=1',
                                               if_else(ans==4, 'Au=0',
                                                       if_else(ans==5|ans==6, 'B', 
                                                               if_else(ans==7, 'Bu=1', 'Bu=0'))))))

df1 <- df1 %>% mutate(ansVar3 = if_else(ans==1, 'A=1',
                                        if_else(ans==2, 'A=0',
                                                if_else(ans==3, 'Au=1',
                                                if_else(ans==4, 'Au=0',
                                                        if_else(ans==5, 'B=1', 
                                                                if_else(ans==6, 'B=0',
                                                                if_else(ans==7, 'Bu=1', 'Bu=0'))))))))


# Split them by probgroup here, so they can go against the relevant model pred group for comparison
pg1 <- df1 %>% filter(probgroup==1) # 80 obs of 19
pg2 <- df1 %>% filter(probgroup==2) # 46 obs of 19
pg3 <- df1 %>% filter(probgroup==3) # 54 obs of 19 

# Now summarise. For first round of plots , do ansVar=8 to see everything, so ansVar3
# If want A=a, or just 'A', take ansVar2 later
pg1prop <- pg1 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))
pg2prop <- pg2 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))
pg3prop <- pg3 %>% group_by(trialtype, ansVar3) %>% summarise(n=n()) %>% mutate(prop = n/sum(n))

# Now save
save(df1, pg1, pg2, pg3, pg1prop, pg2prop, pg3prop, file="../processed_data/processed_data.Rdata")

